### ISSUE TITLE
Provide support for multiple page books

### ISSUE THREAD

**Issue by uzza1hossain** [meparth/bangla-boi-api#1]
Example book url: https://www.ebanglalibrary.com/books/%E0%A6%AC%E0%A7%8D%E0%A6%B2%E0%A7%8D%E0%A6%AF%E0%A6%BE%E0%A6%95-%E0%A6%AC%E0%A7%81%E0%A6%A6%E0%A7%8D%E0%A6%A7%E0%A6%BE-%E0%A6%B0%E0%A6%AC%E0%A6%BF%E0%A6%A8-%E0%A6%9C%E0%A6%BE%E0%A6%AE%E0%A6%BE/

This book have total 58 chapters. First page cover 49 chapters.
50-58 in the second pages.

Is it possible to download all the chapter?

**Comment by meparth** [comment]
i think for now it can be done by providing the urls of each page one by one. In your case, there will be two separate epub files.

**Comment by uzza1hossain** [comment]
The problem is, there is no separate url for second page. Did you check the url I provided? 
Kindly check it, you will understand.

**Comment by uzza1hossain** [comment]
However, If you don't want to implement this feature or can't implement this feature, that's okay. 
I understand, You can close the issue.

**Comment by meparth** [comment]
yeah i cannot go to the second page of the link you gave, its loading forever.
